In [1]:
import tensorflow as tf

In [2]:
inputs = tf.random.normal([32, 10, 8])

In [3]:
inputs

<tf.Tensor: shape=(32, 10, 8), dtype=float32, numpy=
array([[[-0.96721214,  0.40373224, -0.74434906, ...,  0.3962682 ,
         -0.15046868, -0.215136  ],
        [-2.2754204 , -0.7144877 ,  0.41786787, ..., -0.8576336 ,
          0.65680975, -0.18057741],
        [ 1.8278099 ,  0.15481734, -0.17198919, ...,  1.8385226 ,
          0.26569715, -0.5827259 ],
        ...,
        [ 0.41822144, -0.42267326,  0.11152183, ...,  0.14401893,
         -0.3994447 , -0.11547012],
        [-0.41480756,  1.0593779 , -0.2694964 , ...,  0.83176994,
          0.9767616 , -0.8516243 ],
        [ 1.4832373 ,  0.48770455,  0.978535  , ...,  0.29875013,
         -0.84944826, -0.6064818 ]],

       [[ 0.1057469 , -2.8538413 ,  0.6896687 , ...,  1.2454469 ,
          0.6190778 , -1.07913   ],
        [-1.0028394 ,  0.2582283 , -1.6323948 , ..., -2.119204  ,
          1.539598  , -1.6212388 ],
        [ 0.7581547 , -1.7630371 , -0.39298454, ...,  0.57524467,
          1.2557578 , -0.8311442 ],
        ...,
 

In [5]:
lstm = tf.keras.layers.LSTM(4)
output = lstm(inputs)


In [6]:
output

<tf.Tensor: shape=(32, 4), dtype=float32, numpy=
array([[ 0.35891378,  0.02555304,  0.35924208,  0.24291737],
       [-0.56004333, -0.03289614,  0.3659145 ,  0.15905508],
       [-0.3368716 , -0.22344063,  0.55728066, -0.0692952 ],
       [-0.03161412,  0.11446089,  0.3168618 , -0.34705743],
       [-0.29098657,  0.07689756, -0.2720586 , -0.03361539],
       [-0.33036274,  0.19337177,  0.19400501, -0.25222084],
       [ 0.27395368,  0.15789218,  0.12909147,  0.07912619],
       [-0.15876934,  0.35152608, -0.33629492, -0.268789  ],
       [ 0.067332  , -0.01402214,  0.01973805,  0.06641507],
       [ 0.1643007 , -0.02062006,  0.17693444, -0.0499724 ],
       [-0.25169465,  0.09285326, -0.06892808,  0.1125147 ],
       [ 0.3139661 ,  0.22859147,  0.30761945, -0.10676587],
       [-0.18006407,  0.01700202,  0.191857  , -0.10582963],
       [-0.34142217, -0.2900842 ,  0.17660166, -0.17565487],
       [ 0.00643548, -0.00069254, -0.23296902, -0.16142815],
       [-0.07770142, -0.36355522,  0

In [7]:
from tensorflow.keras.models import load_model


In [8]:
model = load_model("model/lstm_classifier.keras")

c:\Users\maphq\miniconda3\Lib\site-packages\keras\src\saving\saving_lib.py:396: UserWarning: Skipping variable loading for optimizer 'adam', because it has 70 variables whereas the saved optimizer has 52 variables. 
  trackable.load_own_variables(weights_store.get(inner_path))


ValueError: A total of 3 objects could not be loaded. Example error message for object <LSTMCell name=lstm_cell, built=True>:

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

List of objects that could not be loaded:
[<LSTMCell name=lstm_cell, built=True>, <LSTMCell name=lstm_cell, built=True>, <LSTMCell name=lstm_cell, built=True>]